### ISSUE TITLE
openHAB-2.3.0-SNAPSHOT versions

### ISSUE THREAD

**Issue by WizBangCrash** [itn3rd77/openhab-synology-spk#7]
Question:
Are you planning to generate a new install for each snapshot of 2.3.0?

I was wondering how I'd upgrade to a later version once I'd switched to 2.3.0.
One option is for me to pull my finger out and get a VM set up to be able to build my own releases from my fork :-)
Is there another option of the 2.3.0 installer checking to see if there is a later build on openHAB.ci.cloudbees.com and give the user the option to use that instead.

Do you had any thoughts on this?

**Comment by itn3rd77** [comment]
Hi,

I am planing to build a snapshot package at least once a day and upload to http://spk.i-matrixx.de.
Should not be a big deal but time is short as always :-)

Next step is to get the https://github.com/jdel/sspks fixed to handle Beta packages correct. At the moment if you would add the package repository you have no chance to install the stable openHAB 2.2 package because the openHAB 2.3 package has a higher version number. It is flagged as Beta but [sspks](https://github.com/jdel/sspks) doesn't handle this correct. To bad Synology doesn't provide any documentation for running an own repository. If you have time and knowledge with PHP and analyzing network traffic you are welcome to get your hands dirty.

**Comment by WizBangCrash** [comment]
Sorry Ingo. This is an area I have no experience in.  I'm gonna focus on my openHAB environment for now. I have a lot of devices I want to get under control :-)
I'll check in to see how your are doing from time to time and if I get some spare time I'll be more than happy to offer some help.
Keep up the good work as I bet there are a lot of Synology users who will benefit from what you're doing.

**Comment by itn3rd77** [comment]
Hi,

daily snapshot builds should arrive now once a day at 02:30 o'clock.
These automatic builds are not tested, so be careful and do a backup. You can always download a previous version and do a clean install (while preserving the openhab share).

Have fun ....
